### ISSUE TITLE
Connection issues in FT mode

### ISSUE THREAD

**Issue by demelvin** [nats-io/stan.js#178]
Hi all 👋 

I'm having an issue with the clients ability to establish an initial connection when running in [fault tolerance (FT) mode](https://docs.nats.io/nats-on-kubernetes/stan-ft-k8s-aws) within a k8s cluster.

**Behavior**
- Run Node.js server, nats client connects to FT leader
- Delete leader pod, client re-connects = expected/perfect
- Restart Node.js server

**Result**
- Client connection is closed on startup. 
- `error` event fires with the following message:

```
{
    "name": "NatsError",
    "message": "stan: connect request timeout",
    "code": "stan: connect request timeout",
    "chainedError": {
        "name": "NatsError",
        "message": "The request timed out for subscription id: -1",
        "code": "REQ_TIMEOUT"
    }
}
```

- `close` event fires, `process.exit()` is called, server restarts over and over again repeating the above resulted steps until a connection can be established.

**Expected Result**
Client connects first time without having to restart multiple times until a connection is established.

**Nats Streaming Version**
Docker Image `nats-streaming:latest`
__Embedded Nats Server__

**Client Version**
`latest (v0.3.3-0)`

I've been combing through the docs, github issues, as well as experimenting with various settings on both the deployment and the client. Any ideas on how to solve this?  

Thank you in advance for your help.

**Comment by aricart** [comment]
@demelvin the default `connectTimeout` for protocol exchanges is set to `2000`, wondering if it needs to be higher on your setup.

**Comment by kozlovic** [comment]
> Delete leader pod, client re-connects = expected/perfect

Could you clarify if by that you mean that the NATS connection was reconnected, or the streaming one? As you know, there is no TCP connection between a client and the streaming server, so a streaming connection is more like a "session". So when NATS can reconnect to a NATS Server (even if embedded in Streaming server), this does not mean that the streaming connection between the streaming server and client is actually restored.

Have you checked the server log of the non deleted pod to see if one of the standby is properly becoming the active server? You could also run the servers with -SD and get a bit more streaming debugging to see what happens when you restart your Node.js server and it fails to connect (assuming that it reaches any of the existing Streaming pods).

**Comment by demelvin** [comment]
@aricart 

Thanks for the suggestion, I'll try bumping up the `connectTimeout` setting on the client and see if that resolves this. 

@kozlovic 

> Could you clarify if by that you mean that the NATS connection was reconnected

The connection I was referring to was specifically the Node.js client connection. After deleting the leader pod the client event `"reconnect"` fires and the connection to the new leader is successful. I was tailing the logs of each pod while testing but the logs were a bit convoluted because I was running the container with the `-DV` flag. I'll try running with the `-SD` flag as you suggested. Hopefully that will reveal an anomaly within my k8s and/or client config. 

Unfortunately I'm dealing with production issues this morning. I should be able to test this out and report back my findings later today.

Thanks again for your help guys. It's very much appreciated.

**Comment by aricart** [comment]
@demelvin just to reiterate, `reconnect` is just the nats connection, the timeout on the protocol exchange indicates that the nats-streaming-server was not available at the time of the request (even if the nats-server is).

**Comment by demelvin** [comment]
@aricart I only included the re-connect in my initial comment because I thought it might help however, the main issue is when the server is started|restarted it simply will not connect to NATS and the node process must be restarted a few times before it is successful. My apologies for any confusion there.

I played around with the `connectTimeout` setting as well as enabled the `-SD` option on the Stan k8s deployment. 

### `connectTimeout`

The `connectTimeout` setting unfortunately did not change anything. I tried a range with this setting. Initially setting this to 5 seconds (5000 millis) and bumping it up all the way to 1 minute. Although the client did wait for the specified period the timeout eventually happened.

### `-SD` Observations

When connecting I'm using a uuid as the client id so it should be unique each time the node client attempts to connect. I was not able to see any indication of this client attempting to connect to NATS when the timeout occurs which is strange. Once the client successfully connects I can see it in the logs:

e.g. 
```
[1] 2020/06/30 03:32:06.582179 [DBG] STREAM: [Client:4289c391-ef23-4dac-84ec-0ca4acb77c47] Connected (Inbox=_INBOX.JR2M92VGT2LOMKX2BV53Y4)
```

Whats even more strange is successful / unsuccessful connection attempts seem to be completely random. Sometimes the `stan.js` client connects immediately, sometimes it takes 3-4 attempts 🤷‍♂️ 

I'm seeing the same type of behavior within the cluster as well as on my local machine which makes me think that perhaps something is up with the ingress or the k8s service itself. I'm going to go over the [setup documentation](https://docs.nats.io/nats-on-kubernetes/stan-ft-k8s-aws) one more time to see if there is something I missed.

**Workaround**
This is the workaround I've currently implemented to get around this. It's not ideal but seems to work.

- Start the server and attempt to connect to NATS. 
- Add connection event listeners
- If `close` event fires rinse and repeat the above until a successful connection is made

Thanks again for your help with this. I'll post again here should I have anything useful to add.

**Comment by aricart** [comment]
> When connecting I'm using a uuid
The client UUID can be (and in some cases should be) stable across process invocations. NATS doesn't care about the client id (it does report a client `name` if you set it on the nats connection options). You might consider specifying the same UUID as the stan client ID and as the client `name`).

**Comment by aricart** [comment]
Just to make sure, I did [a small gist that sets up 2 nats-streaming-servers in cluster mode using FT](https://gist.github.com/aricart/a575e518d85d4d78a9062d50281c3840). You can `control-c` the servers one at time, both etc, and see what the client is doing. The client publishes a message every second, so the expected behaviour is that you see a message printed:

```
connected to nats://localhost:4222
[13]: 1
[14]: 2
[15]: 3
[16]: 4
[17]: 5
[18]: 6
[19]: 7
disconnected
reconnected to nats://localhost:2224
[20]: 8
[21]: 9
[22]: 10
[23]: 11
[24]: 12
[25]: 13
...
[41]: 29
[42]: 30
[43]: 31
[44]: 32
[45]: 33
[46]: 34
[47]: 35
[48]: 36
[49]: 37
^C
```

**Comment by demelvin** [comment]
@aricart Thank you for providing that gist. Running this locally I can see the desired FT behavior.

After looking over the NATS streaming FT documentation and making some changes to my k8s manifest the client is connecting just fine now. The `close` event does still fire every once in awhile when I test pod deletions (e.g. stan-0, stan-1, stan-2) but ultimately this is a k8s misconfiguration and not a stan.js client issue.

In case this might help somebody else. I added the following to my container args within the k8s deployment manifest. After doing this the client is able to connect successfully on server startup/restart without issue.

```
- '--ft_group'
- 'ft'
- '--cluster'
- 'nats://0.0.0.0:6222'
- '--cluster_node_id'
- '$(POD_NAME)'
- '--routes'
- 'nats://stan:6222'
- '--cluster_peers'
- 'stan-0, stan-1, stan-2'
```

Closing issue. Thanks again for all your help 👍

**Comment by kozlovic** [comment]
@demelvin Following the link that you originally posted, it does already configure the ft_group_name, so you should not have to pass additional args? (https://docs.nats.io/nats-on-kubernetes/stan-ft-k8s-aws#setting-up-the-nats-streaming-cluster)
Maybe @wallyqs can comment on that.

Definitively, you should NOT pass `--cluster_peers` simply because this is for Streaming clustering mode, which is opposite to running in FT mode. (it won't hurt specifying it and will be ignored, but could be misleading).

**Comment by demelvin** [comment]
@kozlovic Thanks for the suggestion. I edited my original comment, removing the `cluster_peers` argument. 

I found not providing the `--cluster`, the `--routes`, and the `--cluster_node_id` options in the k8s config I was basically back at square one which was the `stan.js` node client connecting only sometimes. 

I'll play around with it some more. Thanks again.

**Comment by kozlovic** [comment]
I am happy that it works for you and could leave at that, but again, if you followed https://docs.nats.io/nats-on-kubernetes/stan-ft-k8s-aws, I see that it already has the cluster/routes configured:
```
    cluster {
      port: 6222
      routes [
        nats://stan:6222
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 10
    }
```
So you should not have to pass it through command line.

And again, `--cluster_node_id` is for NATS Streaming Cluster mode, which is different from FT mode, and should not be used in that case.
Maybe if you were to provide the whole config, @wallyqs can have a look and see what's wrong.

**Comment by demelvin** [comment]
@kozlovic I'd be happy to provide my config, any help to resolve is welcome here. 

**Several things to note here:**

- I'm running my cluster on Digital Ocean not AWS
- I'm using SQL store not file store.
- I'm not using a k8s `ConfigMap` but rather just passing the config options as args to the container within the `StatefulSet`

Please let me know if you see any improvements or changes that need be made with this setup. I did not see an option to provide the `cluster_advertise` or `connect_retries` to the docker image, perhaps that is the issue 🤔 

#### k8s Manifest

```
---
apiVersion: v1
kind: Service
metadata:
  name: stan
  labels:
    app: stan
spec:
  selector:
    app: stan
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: console
    port: 8282
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stan
  labels:
    app: stan
spec:
  selector:
    matchLabels:
      app: stan
  serviceName: stan
  replicas: 1
  template:
    metadata:
      labels:
        app: stan
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: stan
        image: nats-streaming:latest
        ports:
        # In case of NATS embedded mode expose these ports
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        args:
         - "--cluster_id"
         - "test-cluster"
         - "--store"
         - "sql"
         - "--sql_driver"
         - "postgres"
         - "--sql_source"
         - "<DB_CONNECTION_URL_GOES_HERE>"
         - "-p"
         - "4222"
            - '--max_channels'
            - '0'
            - '--max_subs'
            - '0'
            - '--max_msgs'
            - '0'
            - '--ft_group'
            - 'test-cluster'
            - '--cluster'
            - 'nats://0.0.0.0:6222'
            - '--cluster_node_id'
            - '$(POD_NAME)'
            - '--routes'
            - 'nats://stan:6222'
            - '-SDV'
.....
```

#### stan.js client

```
const sc = stan.connect(`test-cluster`, `test-client`, {
  url: 'nats://stan:4222',
  maxReconnectAttempts: 10,
  reconnectTimeWait: 5 * 1000,
  json: true,
  waitOnFirstConnect: true,
});
```

Hope this reveals something incorrect with the config or setup. Please let me know if something sticks out. 

Thanks again everyone 👍

**Comment by kozlovic** [comment]
Yes, some of the configuration cannot be set through command line, so you would need to use a configuration file. I don't know much about k8s so would let @wallyqs comment, but I see several things:
- you have `replicas: 1`, so it looks to me that there would be only one instance, so really if that pod dies, there is no server running?
- in our doc there is this:
```
        # Required to be able to define an environment variable
        # that refers to other environment variables.  This env var
        # is later used as part of the configuration file.
       env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).stan.$(POD_NAMESPACE).svc
...
```
That's how then in the config you would be able to specify `cluster_advertise: $CLUSTER_ADVERTISE` and the routes would be pointing to any `stan` pod.
- I still don't understand why you are required to have this in your config:
```
 - '--cluster_node_id'
 - '$(POD_NAME)'
```
this is clustering mode, not FT. I believe that you said if you remove this it "does not work", right?
